### ISSUE TITLE
Enhancement of calendar view

### ISSUE THREAD

**Issue by Blutimauge** [Blutimauge/Application#10]
La calendar view è pronta, ci sono alcuni miglioramenti da fare:
- Gli eventi giornalieri si protraggono anche fino all'1 del giorno successivo, da fixare
- Ogni evento viene ripetuto 3 volte nel suo spazio, schiacciandosi e rendendolo illeggibile, capire perché.
- Cercare magari di portare il calendario all'apertura all'ora corrente, per evitare di dover scrollare ogni volta

**Comment by edoardogiacomello** [comment]
Per il punto 3 penso sia relativa alla issue che ho aperto sulla visualizzazione del Calendario. Secondo me è meglio centrare la view nella fascia 8-17 o 8-23 e lasciare la notte da scrollare su o giù

**Comment by edoardogiacomello** [comment]
Nota sul punto 2:
Il numero di duplicazioni è ora dipendente dalla quantità di scrolling e forse dal numero di calendari proposti. Sicuramente c'è da fare una query che specifichi l'ID del calendario scelto.

**Comment by Blutimauge** [comment]
Il punto 2 è stato risolto, gli altri li apro in issue separate
