### ISSUE TITLE
Center the view on current hour

### ISSUE THREAD

**Issue by Blutimauge** [Blutimauge/Application#20]
Quando si apre la view del calendario, sarebbe meglio centrarla sull'ora corrente (il giorno già lo fa) per evitare scroll inutili

**Comment by edoardogiacomello** [comment]
Io proporrei una visualizzazione che prenda dentro il range 8-17.. o comunque quello che di solito interessa di più

**Comment by Blutimauge** [comment]
La visuale degli eventi ristretta adesso copre quasi tutto il giorno, il problema non persiste
