### ISSUE TITLE
"First Login"

### ISSUE THREAD

**Issue by edoardogiacomello** [Blutimauge/Application#7]
questa variabile è da settare al primo FLOW COMPLETATO della home, poiché in qualsiasi altro caso significherebbe che il tutorial è stato interrotto in modo inaspettato (o l'utente ha chiuso l'app) e quindi il tutorial deve essere visualizzato di nuovo.

**Comment by Blutimauge** [comment]
Risolto, alla chiusura dell'app si riprende sempre dalla prima del tutorial fino a quando non viene confermato nella terza pagina di andare nella main page.
