### ISSUE TITLE
Generalize query in CalendarFetcher

### ISSUE THREAD

**Issue by Blutimauge** [Blutimauge/Application#8]
Nel Calendar Fetcher ho cambiato il nome della funzione getCalendarModels in calendarQuery mettendogli come parametro la proiezione da eseguire, teoricamente per evitare di avere mille funzioni diverse che si differenziano solo per quella variabile, e lo stesso ho fatto con eventsQuery.

Poi però mi sono accorto che all'interno di questa funzione viene creato un oggetto che ha diversi parametri a seconda di quale proiezione stiamo facendo, non so se cercare di parametrizzare anche questa cosa oppure pensi che sia meglio tornare indietro e fare una funzione per ogni proiezione? 
(in caso di revert, faccio io)

**Comment by edoardogiacomello** [comment]
voto per il revert, perche` parametrizzare i risultati puo` essere difficile visto che vengono restituiti in un listener. L` idea principale per evitare di dover riconoscere il tipo di dato ritornato era di inviare il comando di "build" al fetcher, e alla response farsi restituire il risultato tramite l`apposito getter.

**Comment by Blutimauge** [comment]
Revertato, in attesa di aggiungere l'async per vedere se crasha

**Comment by edoardogiacomello** [comment]
Aperta issue apposita.
